import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import Image from "next/image";
import ProfilePic from "../../public/images/profile/eder.png";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  const textTitle = "Eu sou Eder, um desenvelvedor fullstack.";
  const textSubtitle =
    "Tenho habilidades em desenvolvimento web, mobile e desktop.";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-full">
        <Layout className="pt-2">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={ProfilePic} alt="logo" className="w-full h-auto" />
            </div>
            <div>
              <h1 className="flex flex-col items-center self-center">
                <AnimatedText
                  text={textTitle}
                  className="!text-6xl !text-left"
                />
              </h1>

              <p className="my-4 text-base font-medium">{textSubtitle}</p>
              <div className="flex items-center self-start mt-2 gap-2">
                <Link
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  href="/Profile.pdf"
                  target={"_blank"}
                  download={true}
                >
                  CV/Resume <LinkArrow className={"w-6  ml-1"} />
                </Link>
                <Link
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  href="mailto:eder.sena@live.com"
                >
                  Contato
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
